const state = () => ({
    all: [
        {
            id: 1,
            name: 'Linen crochet trim t-shirt',
            price: 191.00,
            offer: true,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/img1.jpg'),
            imageHover: require('../assets/img/img-hover1.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 2,
            name: 'Neck empire sleeve t-shirts',
            price: 300.00,
            offer: false,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/img2.jpg'),
            imageHover: require('../assets/img/img-hover2.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 3,
            name: 'Mermaid pencil midi lace',
            price: 166.00,
            offer: true,
            offerPrice: 5,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/img3.jpg'),
            imageHover: require('../assets/img/img-hover3.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 4,
            name: 'Criss-cross V neck bodycon',
            price: 200.00,
            offer: false,
            offerPrice: 7,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/img4.jpg'),
            imageHover: require('../assets/img/img-hover4.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 5,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/img5.jpg'),
            imageHover: require('../assets/img/img-hover5.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 6,
            name: 'Tenku remastered',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/img6.jpg'),
            imageHover: require('../assets/img/img-hover6.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 7,
            name: 'Women\'s sherpa lined hoodie',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/img7.jpg'),
            imageHover: require('../assets/img/img-hover7.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 8,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../assets/img/img8.jpg'),
            imageHover: require('../assets/img/img-hover8.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 9,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/bestseller-img1.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img1.jpg'),
            timePeriod: true,
            dateTime: new Date("August 19, 2022 17:00:00 PDT")
        },
        {
            id: 10,
            name: 'Neck empire sleeve t-shirts',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/bestseller-img2.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img2.jpg'),
            timePeriod: false,
            trendingProducts: false,
            dateTime: new Date("August 19, 2021 17:00:00 PDT")
        },
        {
            id: 11,
            name: 'Mermaid pencil midi lace',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/bestseller-img3.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img3.jpg'),
            timePeriod: true,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 12,
            name: 'Criss-cross V neck bodycon',
            price: 191.00,
            offer: false,
            offerPrice: 4,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../assets/img/bestseller-img4.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img4.jpg'),
            timePeriod: false,
            dateTime: new Date("April 19, 2020 17:00:00 PDT")
        },
        {
            id: 13,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/trending-img1.jpg'),
            imageHover: require('../assets/img/trending-hover-img1.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 14,
            name: 'Tenku remastered',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/trending-img2.jpg'),
            imageHover: require('../assets/img/trending-hover-img2.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 15,
            name: 'Women\'s sherpa lined hoodie',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../assets/img/trending-img3.jpg'),
            imageHover: require('../assets/img/trending-hover-img3.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 16,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trendingOne: true,
            trending: true,
            image: require('../assets/img/trending-img4.jpg'),
            imageHover: require('../assets/img/trending-hover-img4.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 17,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            trendingOne: true,
            offerPrice: 7,
            image: require('../assets/img/trending-img5.jpg'),
            imageHover: require('../assets/img/trending-hover-img5.jpg'),
        },
        {
            id: 18,
            name: 'Tenku remastered',
            price: 177.00,
            offer: false,
            trendingOne: true,
            offerPrice: 7,
            image: require('../assets/img/trending-img6.jpg'),
            imageHover: require('../assets/img/trending-hover-img6.jpg'),
        },
        {
            id: 19,
            name: 'Women\'s sherpa lined hoodie',
            price: 300.00,
            offer: true,
            trendingOne: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img7.jpg'),
            imageHover: require('../assets/img/trending-hover-img7.jpg'),
        },
        {
            id: 20,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            trendingOne: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img8.jpg'),
            imageHover: require('../assets/img/trending-hover-img8.jpg'),
        },
        {
            id: 20,
            name: 'The cosmic cornucopia',
            price: 191.00,
            offer: false,
            trendingOne: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img1.jpg'),
            imageHover: require('../assets/img/trending-hover-img1.jpg'),
        },
        {
            id: 20,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            trendingOne: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img2.jpg'),
            imageHover: require('../assets/img/trending-hover-img2.jpg'),
        },
        {
            id: 20,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            trendingOne: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img3.jpg'),
            imageHover: require('../assets/img/trending-hover-img3.jpg'),
        },
        {
            id: 21,
            name: 'Linen crochet trim',
            price: 191.00,
            latestOne: true,
            offer: true,
            latest: false,
            bestSellers: false,
            trending: false,
            offerPrice: 3,
            image: require('../assets/img/sunglasses-image/img1.jpg'),
        },
        {
            id: 22,
            name: 'Neck empire sleeve',
            price: 300.00,
            latestOne: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/sunglasses-image/img2.jpg'),
        },
        {
            id: 23,
            name: 'Mermaid pencil midi',
            price: 166.00,
            latestOne: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/sunglasses-image/img3.jpg'),
        },
        {
            id: 24,
            name: 'Linen crochet trim',
            price: 191.00,
            latestTwo: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/sunglasses-image/img4.jpg'),
        },
        {
            id: 25,
            name: 'Neck empire sleeve',
            price: 300.00,
            latestTwo: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/sunglasses-image/img5.jpg'),
        },
        {
            id: 26,
            name: 'Mermaid pencil midi',
            price: 166.00,
            latestTwo: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/sunglasses-image/img6.jpg'),
        },
        {
            id: 27,
            name: 'Linen crochet trim',
            price: 191.00,
            special: true,
            specialOne: false,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img1.jpg'),
        },
        {
            id: 28,
            name: 'Heartland Alabama',
            price: 300.00,
            special: true,
            specialOne: false,
            sale: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img2.jpg'),
        },
        {
            id: 29,
            name: 'Mermaid pencil midi',
            price: 250.00,
            special: true,
            specialOne: false,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img3.jpg'),
        },
        {
            id: 30,
            name: 'Criss-cross',
            price: 191.00,
            special: true,
            specialOne: false,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img4.jpg'),
        },
        {
            id: 31,
            name: 'V neck bodycon',
            price: 214.00,
            special: true,
            specialOne: false,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img5.jpg'),
        },
        {
            id: 32,
            name: 'cosmic cornucopia',
            price: 541.00,
            special: true,
            specialOne: false,
            sale: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img6.jpg'),
        },
        {
            id: 33,
            name: 'Tenku remastered',
            price: 540.00,
            special: true,
            specialOne: false,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img7.jpg'),
        },
        {
            id: 34,
            name: 'Lined hoodie',
            price: 191.00,
            special: true,
            specialOne: false,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img8.jpg'),
        },
        {
            id: 35,
            name: 'Linen crochet trim',
            price: 191.00,
            special: false,
            specialOne: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img6.jpg'),
        },
        {
            id: 36,
            name: 'Heartland Alabama',
            price: 300.00,
            special: false,
            specialOne: true,
            sale: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img5.jpg'),
        },
        {
            id: 37,
            name: 'Mermaid pencil midi',
            price: 250.00,
            special: false,
            specialOne: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img1.jpg'),
        },
        {
            id: 38,
            name: 'Criss-cross',
            price: 191.00,
            special: false,
            specialOne: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img2.jpg'),
        },
        {
            id: 39,
            name: 'V neck bodycon',
            price: 214.00,
            special: false,
            specialOne: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img4.jpg'),
        },
        {
            id: 40,
            name: 'cosmic cornucopia',
            price: 541.00,
            special: false,
            specialOne: true,
            sale: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img3.jpg'),
        },
        {
            id: 41,
            name: 'Tenku remastered',
            price: 540.00,
            special: false,
            specialOne: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img7.jpg'),
        },
        {
            id: 42,
            name: 'Lined hoodie',
            price: 191.00,
            special: false,
            specialOne: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img1.jpg'),
        },
        {
            id: 43,
            name: 'Mermaid pencil midi',
            price: 250.00,
            special: false,
            specialOne: false,
            specialTwo: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img1.jpg'),
        },
        {
            id: 44,
            name: 'Criss-cross',
            price: 191.00,
            special: false,
            specialOne: false,
            specialTwo: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img2.jpg'),
        },
        {
            id: 45,
            name: 'V neck bodycon',
            price: 214.00,
            special: false,
            specialOne: false,
            specialTwo: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img4.jpg'),
        },
        {
            id: 46,
            name: 'cosmic cornucopia',
            price: 541.00,
            special: false,
            specialOne: false,
            specialTwo: true,
            sale: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img3.jpg'),
        },
        {
            id: 47,
            name: 'Tenku remastered',
            price: 540.00,
            special: false,
            specialOne: false,
            specialTwo: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img7.jpg'),
        },
        {
            id: 48,
            name: 'Lined hoodie',
            price: 191.00,
            special: false,
            specialOne: false,
            specialTwo: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img1.jpg'),
        },
        {
            id: 49,
            name: 'Mermaid pencil midi',
            price: 250.00,
            specialThree: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img3.jpg'),
        },
        {
            id: 50,
            name: 'Criss-cross',
            price: 191.00,
            specialThree: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img1.jpg'),
        },
        {
            id: 51,
            name: 'V neck bodycon',
            price: 214.00,
            specialThree: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img2.jpg'),
        },
        {
            id: 52,
            name: 'cosmic cornucopia',
            price: 541.00,
            specialThree: true,
            sale: true,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img5.jpg'),
        },
        {
            id: 53,
            name: 'Tenku remastered',
            price: 540.00,
            specialThree: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img6.jpg'),
        },
        {
            id: 54,
            name: 'Lined hoodie',
            price: 191.00,
            specialThree: true,
            sale: false,
            offer: true,
            offerPrice: 3,
            image: require('../assets/img/product-image/img4.jpg'),
        },
        {
            id: 55,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: true,
            trendingOne: false,
            trendingTwo: true,
            image: require('../assets/img/trending-img2.jpg'),
            imageHover: require('../assets/img/trending-hover-img2.jpg'),
        },
        {
            id: 56,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            trendingOne: false,
            trendingTwo: true,
            offerPrice: 7,
            image: require('../assets/img/trending-img5.jpg'),
            imageHover: require('../assets/img/trending-hover-img5.jpg'),
        },
        {
            id: 57,
            name: 'Tenku remastered',
            price: 177.00,
            offer: false,
            trendingOne: false,
            trendingTwo: true,
            offerPrice: 7,
            image: require('../assets/img/trending-img7.jpg'),
            imageHover: require('../assets/img/trending-hover-img7.jpg'),
        },
        {
            id: 58,
            name: 'Women\'s sherpa lined hoodie',
            price: 300.00,
            offer: true,
            trendingOne: false,
            trendingTwo: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img1.jpg'),
            imageHover: require('../assets/img/trending-hover-img1.jpg'),
        },
        {
            id: 59,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            trendingOne: false,
            trendingTwo: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img6.jpg'),
            imageHover: require('../assets/img/trending-hover-img6.jpg'),
        },
        {
            id: 60,
            name: 'The cosmic cornucopia',
            price: 191.00,
            offer: false,
            trendingOne: false,
            trendingTwo: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img2.jpg'),
            imageHover: require('../assets/img/trending-hover-img2.jpg'),
        },
        {
            id: 61,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            trendingOne: false,
            trendingTwo: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img4.jpg'),
            imageHover: require('../assets/img/trending-hover-img4.jpg'),
        },
        {
            id: 62,
            name: 'Belted chino trousers polo',
            price: 191.00,
            offer: false,
            trendingOne: false,
            trendingTwo: true,
            offerPrice: 4,
            image: require('../assets/img/trending-img8.jpg'),
            imageHover: require('../assets/img/trending-hover-img8.jpg'),
        },
        
        {
            id: 9,
            name: 'The cosmic cornucopia',
            price: 150.00,
            offer: true,
            bestSellersOne: true,
            offerPrice: 7,
            image: require('../assets/img/bestseller-img5.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img5.jpg'),
        },
        {
            id: 10,
            name: 'Neck empire sleeve t-shirts',
            price: 177.00,
            offer: false,
            bestSellersOne: true,
            offerPrice: 7,
            image: require('../assets/img/bestseller-img6.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img6.jpg'),
        },
        {
            id: 11,
            name: 'Mermaid pencil midi lace',
            price: 300.00,
            offer: true,
            bestSellersOne: true,
            offerPrice: 4,
            image: require('../assets/img/bestseller-img7.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img7.jpg'),
        },
        {
            id: 12,
            name: 'Criss-cross V neck bodycon',
            price: 191.00,
            offer: false,
            bestSellersOne: true,
            offerPrice: 4,
            image: require('../assets/img/bestseller-img8.jpg'),
            imageHover: require('../assets/img/bestseller-hover-img8.jpg'),
        },
    ]
});

export default {
    state
};